[project]
name = "translator-agent-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai[agents]>=1.82.1",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
